#!/bin/bash

VIM_DOWNLOADS="$HOME/Downloads/vim_plugins"

function on_path {
  path=`which $1`
  [ -x "$path" ]
}

function prerequisites {
   for command in $*; do
     on_path $command || (echo "Missing prerequisite '$command'."; exit 1)
   done
}

function installing {
  echo "**********************************************************"
  echo "Installing $*"
  echo "**********************************************************"
}

function installed {
  echo "Skipping $*. Already installed."
}

function clone_or_pull {
  if [ -d $2/.git ]; then
    pushd $2
    git pull origin master
    popd
  else
    git clone $1
  fi
}

function install_home {
  installing "home config..."
  cp -R home/* $HOME
}

function install_rvm {
  if ! on_path rvm; then
    installing RVM
    bash < <( curl http://rvm.beginrescueend.com/releases/rvm-install-head )
  else
    installed RVM
  fi
}

function mk_and_pushd {
	mkdir -p $1
	pushd $1
}

function install_config {
  echo "Copying config files to your home directory."
  cp -Ri home/ $HOME
  echo "Done."
}

function install_ack {
  installing "vim-ack"
  mk_and_pushd $VIM_DOWNLOADS
  clone_or_pull https://github.com/mileszs/ack.vim.git ack.vim
  cp -R ack.vim/plugin ack.vim/doc $HOME/.vim
  popd
  if [ ! -x ~/bin/ack ]; then
    curl http://betterthangrep.com/ack-standalone > ~/bin/ack && chmod 0755 ~/bin/ack
  fi
}

function install_vim_ruby {
  installing "vim-ruby"
  mk_and_pushd $VIM_DOWNLOADS
  clone_or_pull https://github.com/vim-ruby/vim-ruby.git vim-ruby
  ./vim-ruby/bin/vim-ruby-install.rb
  popd
}

function install_vim_rails {
  installing "vim-rails"
  mk_and_pushd $VIM_DOWNLOADS
  clone_or_pull https://github.com/tpope/vim-rails.git vim-rails
  cp -R vim-rails/autoload vim-rails/plugin $HOME/.vim
  popd
}

function install_fugitive {
  installing "vim-fugitive"
  mk_and_pushd $VIM_DOWNLOADS
  clone_or_pull https://github.com/tpope/vim-fugitive.git vim-fugitive
  cp -R vim-fugitive/plugin $HOME/.vim
  popd
}

on_path 'this_wont_be_on_the_path'  && echo "WARNING: The on_path method sees things that shouldn\'t be there"
on_path 'ls' || echo "WARNING: The on_path method doesn\'t see things that should be there"

if ! prerequisites bash curl git;  then
  echo "Missing some prerequisites. Please fix and try again."
  exit 1
fi


echo "All prerequisites met, let's install..."
if [ x$1 == xconfig ]; then
  install_config
else
  install_rvm
  install_vim_ruby
  install_vim_rails
  install_fugitive 
  install_ack
  echo "*******************************************************************************"
  echo "Software install complete, re-run with 'config' parameter to install the config"
  echo "files in your home directory"
  echo "*******************************************************************************"
fi

